; Generated by C2ASM Compiler

section .data
    fmt_int db "%d", 10, 0
    fmt_float db "%f", 10, 0
    fmt_char db "%c", 0
    input_int db "%d", 0

section .text
    global _main
    extern _printf
    extern _scanf

_main::
    push ebp
    mov ebp, esp
    sub esp, 128
    mov esp, ebp
    pop ebp
    ret
    
