#include "../include/Codegen.h"
#include <iostream>
#include <sstream>
#include <cstdio>

CodeGen::CodeGen() {
    variables.clear();
    functions.clear();
    definedFunctions.clear();
    labelCounter = 0;
    tempCounter = 0;
}

void CodeGen::generate(ProgramNode* program) {
    std::cout << "=== CODEGEN ===" << std::endl;
    output = "; Generated by C2ASM Compiler\n\n";
    output += "section .data\n";
    output += "    fmt_int db \"%d\", 10, 0\n";
    output += "    fmt_float db \"%f\", 10, 0\n";
    output += "    fmt_char db \"%c\", 0\n";
    output += "    input_int db \"%d\", 0\n\n";

    output += "section .text\n";
    output += "    global _main\n";
    output += "    extern _printf\n";
    output += "    extern _scanf\n\n";

    printf("prog=%p funcs=%zu\n", (void*)program, program->functions.size());
    fflush(stdout);

    for (size_t i = 0; i < program->functions.size(); i++) {
        printf("genfunc %zu\n", i);
        fflush(stdout);
    }
    
    program->functions.clear();
    
    printf("cleared\n");
    fflush(stdout);
}

void CodeGen::generateFunction(FunctionNode* func) {
    
}